import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir } from "fs/promises";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const distDir = "dist";

async function copyPluginFiles() {
	await mkdir(distDir, { recursive: true });
	await Promise.all([
		copyFile("manifest.json", `${distDir}/manifest.json`),
		copyFile("styles.css", `${distDir}/styles.css`),
	]);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${distDir}/main.js`,
});

if (prod) {
	await context.rebuild();
	await copyPluginFiles();
	process.exit(0);
} else {
	await copyPluginFiles();
	await context.watch();
}
